# Generated by Django 3.2.7 on 2024-04-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('publish_data', models.DateTimeField()),
                ('pages', models.IntegerField()),
                ('hard_cover', models.BooleanField(default=True)),
            ],
        ),
    ]
